name: Windows_x86_64

on:
  workflow_dispatch:

permissions: read-all

env:
  LRS_RUN_WITH_DEB_CONFIG: RelWithDebInfo
  PYTHON_PATH: C:\\hostedtoolcache\\windows\\Python\\3.12.6\\x64\\python.exe
  WIN_BUILD_DIR: C:/lrs_build

jobs:
  windows:
    runs-on: windows-2019
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3.1.4
        with:
          python-version: "3.12.6"

      - name: Enable Long Paths
        shell: powershell
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - name: PreBuild
        shell: bash
        run: |
          mkdir ${{env.WIN_BUILD_DIR}}

      - name: Configure CMake
        shell: bash
        run: |
          LRS_SRC_DIR=$(pwd)
          cd ${{env.WIN_BUILD_DIR}}
          cmake ${LRS_SRC_DIR} -G "Visual Studio 16 2019" -DBUILD_PYTHON_BINDINGS=bool:true -DFORCE_RSUSB_BACKEND=true -DCMAKE_BUILD_TYPE=release -DPYTHON_EXECUTABLE=${{env.PYTHON_PATH}} -DBUILD_SHARED_LIBS=false -DBUILD_EXAMPLES=false -DBUILD_TOOLS=false -DCHECK_FOR_UPDATES=false

      - name: Build
        shell: bash
        run: |
          cd ${{env.WIN_BUILD_DIR}}
          cmake --build . --config Release -- -m

          cp ${{env.WIN_BUILD_DIR}}/Release/*.pyd ${LRS_SRC_DIR}/wrappers/python/pyrealsense2/
          cd ${LRS_SRC_DIR}/wrappers/python/
          ${{env.PYTHON_PATH}} -m pip install -r requirements.txt
          ${{env.PYTHON_PATH}} setup.py bdist_wheel

      - name: Upload Wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: Wheel - ubuntu
          path: ${LRS_SRC_DIR}/wrappers/python/*.whl
